name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'
    paths:
      - 'docker/Dockerfile'
      - '.github/workflows/docker-build-push.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag(s) based on branch
        id: vars
        run: |
          BRANCH=$(echo "${GITHUB_REF#refs/heads/}")
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          if [ "$BRANCH" = "main" ]; then
            echo "tags=ghcr.io/${{ github.repository_owner }}/foundation:latest" >> $GITHUB_OUTPUT
          else
            echo "tags=ghcr.io/${{ github.repository_owner }}/foundation:$BRANCH" >> $GITHUB_OUTPUT
          fi
      
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      
      - name: Check disk usage after cleanup
        run: df -h

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.vars.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
